# frozen_string_literal: true

require "knievel/configuration"
require "knievel/auth/jwt_file_token_source"

# Hand-written extension to the generated `Knievel::Configuration`.
# Adds a `jwt_file` accessor that hooks the file-backed token
# source into the existing `access_token_getter` plumbing — so
# every authenticated request re-reads (or pulls from the
# 30-s in-memory cache, see `Auth::JwtFileTokenSource`) the
# kubelet-rotated file.
#
# Lives outside `lib/knievel/configuration.rb` because that
# file is regenerated by openapi-generator on every spec
# change. This file is preserved by `.openapi-generator-ignore`.
module Knievel
  class Configuration
    # Path to a file containing a bearer JWT (e.g. a Kubernetes
    # ServiceAccount projected token). When set, the contents
    # of the file are used as the bearer token for every
    # request, with a 30-second in-memory cache to avoid disk
    # reads on every call. Takes precedence over
    # `access_token` and `access_token_getter`.
    attr_reader :jwt_file

    def jwt_file=(path)
      @jwt_file = path
      if path.nil?
        @jwt_file_token_source = nil
      else
        @jwt_file_token_source = Knievel::Auth::JwtFileTokenSource.new(path)
      end
    end

    # Override the upstream resolver: if a `jwt_file` is set,
    # read from there; else fall back to the existing
    # `access_token_getter` / `access_token` behavior.
    def access_token_with_refresh
      return @jwt_file_token_source.token if @jwt_file_token_source
      return access_token if access_token_getter.nil?
      access_token_getter.call
    end
  end

  # Top-level `Knievel.configure` so callers can write
  #
  #   Knievel.configure do |c|
  #     c.jwt_file = "/var/run/secrets/knievel/token"
  #   end
  #
  # from a Rails initializer without having to know about
  # `Configuration.default`. Yields the same singleton
  # `Configuration` that `ApiClient.default` uses, so the
  # configuration applies to any `*Api` instance constructed
  # without an explicit client.
  def self.configure
    yield Configuration.default if block_given?
    Configuration.default
  end
end
