=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

module Knievel
  VERSION = '0.1.5'
end
