# -*- encoding: utf-8 -*-

=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "knievel/version"

Gem::Specification.new do |s|
  s.name        = "knievel"
  s.version     = Knievel::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Knievel Ads"]
  s.email       = ["engineering@knievel-ads.com"]
  s.homepage    = "https://github.com/knievel-ads/knievel-ruby"
  s.summary     = "Ruby client for the Knievel ad-serving platform"
  s.description = "Generated client library for the Knievel multi-tenant ad-serving platform."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 3.0"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
