=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::AdLibraryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdLibraryApi' do
  before do
    # run before each test
    @api_instance = Knievel::AdLibraryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdLibraryApi' do
    it 'should create an instance of AdLibraryApi' do
      expect(@api_instance).to be_instance_of(Knievel::AdLibraryApi)
    end
  end

  # unit tests for create_ad_library_item
  # @param org_id 
  # @param create_ad_library_item_request 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItem]
  describe 'create_ad_library_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ad_library_item
  # @param org_id 
  # @param item_id 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItem]
  describe 'get_ad_library_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ad_library_items
  # @param org_id 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItemList]
  describe 'list_ad_library_items test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_ad_library_item
  # @param org_id 
  # @param item_id 
  # @param update_ad_library_item_request 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItem]
  describe 'update_ad_library_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
