=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::AdsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdsApi' do
  before do
    # run before each test
    @api_instance = Knievel::AdsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdsApi' do
    it 'should create an instance of AdsApi' do
      expect(@api_instance).to be_instance_of(Knievel::AdsApi)
    end
  end

  # unit tests for batch_upsert_ads
  # @param project_id 
  # @param batch_upsert_ads_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertAdsResult]
  describe 'batch_upsert_ads test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_ad
  # @param project_id 
  # @param create_ad_request 
  # @param [Hash] opts the optional parameters
  # @return [Ad]
  describe 'create_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ad
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Ad]
  describe 'get_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ads
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [AdList]
  describe 'list_ads test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_ad
  # @param project_id 
  # @param id 
  # @param update_ad_request 
  # @param [Hash] opts the optional parameters
  # @return [Ad]
  describe 'update_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
