=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::AdvertisersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdvertisersApi' do
  before do
    # run before each test
    @api_instance = Knievel::AdvertisersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdvertisersApi' do
    it 'should create an instance of AdvertisersApi' do
      expect(@api_instance).to be_instance_of(Knievel::AdvertisersApi)
    end
  end

  # unit tests for batch_upsert_advertisers
  # &#x60;POST /v1/projects/:project_id/advertisers:batchUpsert&#x60; — bulk by &#x60;externalId&#x60;. Single Postgres transaction; per &#x60;API.md&#x60; \&quot;Write contract\&quot; any per-row failure rolls back the whole batch with &#x60;details[]&#x60; listing every offending row. On success: 200 with the upserted rows in input order.
  # @param project_id 
  # @param batch_upsert_advertisers_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertAdvertisersResult]
  describe 'batch_upsert_advertisers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_advertiser
  # @param project_id 
  # @param create_advertiser_request 
  # @param [Hash] opts the optional parameters
  # @return [Advertiser]
  describe 'create_advertiser test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_advertiser
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Advertiser]
  describe 'get_advertiser test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_advertisers
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [AdvertiserList]
  describe 'list_advertisers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_advertiser
  # @param project_id 
  # @param id 
  # @param update_advertiser_request 
  # @param [Hash] opts the optional parameters
  # @return [Advertiser]
  describe 'update_advertiser test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
