=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::CampaignsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CampaignsApi' do
  before do
    # run before each test
    @api_instance = Knievel::CampaignsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CampaignsApi' do
    it 'should create an instance of CampaignsApi' do
      expect(@api_instance).to be_instance_of(Knievel::CampaignsApi)
    end
  end

  # unit tests for batch_upsert_campaigns
  # @param project_id 
  # @param batch_upsert_campaigns_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertCampaignsResult]
  describe 'batch_upsert_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_campaign
  # @param project_id 
  # @param create_campaign_request 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'create_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_campaign
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'get_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_campaigns
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [CampaignList]
  describe 'list_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_campaign
  # @param project_id 
  # @param id 
  # @param update_campaign_request 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'update_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
