=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::CreativeTemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreativeTemplatesApi' do
  before do
    # run before each test
    @api_instance = Knievel::CreativeTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreativeTemplatesApi' do
    it 'should create an instance of CreativeTemplatesApi' do
      expect(@api_instance).to be_instance_of(Knievel::CreativeTemplatesApi)
    end
  end

  # unit tests for create_creative_template
  # @param project_id 
  # @param create_creative_template_request 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplate]
  describe 'create_creative_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_creative_template
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplate]
  describe 'get_creative_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_creative_templates
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplateList]
  describe 'list_creative_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_creative_template
  # PATCH bumps &#x60;version&#x60; whenever the schema field is provided (per &#x60;API.md&#x60; § 3.6 — schema changes are versioned but do not retroactively re-validate existing creatives).
  # @param project_id 
  # @param id 
  # @param update_creative_template_request 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplate]
  describe 'update_creative_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
