=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::CreativesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreativesApi' do
  before do
    # run before each test
    @api_instance = Knievel::CreativesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreativesApi' do
    it 'should create an instance of CreativesApi' do
      expect(@api_instance).to be_instance_of(Knievel::CreativesApi)
    end
  end

  # unit tests for create_creative
  # @param project_id 
  # @param create_creative_request 
  # @param [Hash] opts the optional parameters
  # @return [Creative]
  describe 'create_creative test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_creative
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Creative]
  describe 'get_creative test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_creatives
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreativeList]
  describe 'list_creatives test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_creative_image
  # Multipart image upload (Phase 3.32). Validates the body against the &#x60;image_upload&#x60; core (size + magic bytes + MIME allow-list), writes through the configured &#x60;ImageStore&#x60;, and updates the creative row&#39;s &#x60;image_url&#x60; in the same transaction. Min role: editor (matches &#x60;createCreative&#x60;).
  # @param project_id 
  # @param id 
  # @param file 
  # @param [Hash] opts the optional parameters
  # @return [Creative]
  describe 'upload_creative_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
