=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::DecisionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DecisionsApi' do
  before do
    # run before each test
    @api_instance = Knievel::DecisionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DecisionsApi' do
    it 'should create an instance of DecisionsApi' do
      expect(@api_instance).to be_instance_of(Knievel::DecisionsApi)
    end
  end

  # unit tests for decisions
  # @param project_id 
  # @param decisions_request 
  # @param [Hash] opts the optional parameters
  # @return [DecisionsResponse]
  describe 'decisions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
