=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = Knievel::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(Knievel::DefaultApi)
    end
  end

  # unit tests for batch_upsert_ads
  # @param project_id 
  # @param batch_upsert_ads_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertAdsResult]
  describe 'batch_upsert_ads test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_upsert_advertisers
  # &#x60;POST /v1/projects/:project_id/advertisers:batchUpsert&#x60; — bulk by &#x60;externalId&#x60;. Single Postgres transaction; per &#x60;API.md&#x60; \&quot;Write contract\&quot; any per-row failure rolls back the whole batch with &#x60;details[]&#x60; listing every offending row. On success: 200 with the upserted rows in input order.
  # @param project_id 
  # @param batch_upsert_advertisers_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertAdvertisersResult]
  describe 'batch_upsert_advertisers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_upsert_campaigns
  # @param project_id 
  # @param batch_upsert_campaigns_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertCampaignsResult]
  describe 'batch_upsert_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_upsert_flights
  # @param project_id 
  # @param batch_upsert_flights_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertFlightsResult]
  describe 'batch_upsert_flights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_upsert_sites
  # @param project_id 
  # @param batch_upsert_sites_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertSitesResult]
  describe 'batch_upsert_sites test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for batch_upsert_zones
  # @param project_id 
  # @param batch_upsert_zones_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertZonesResult]
  describe 'batch_upsert_zones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_ad
  # @param project_id 
  # @param create_ad_request 
  # @param [Hash] opts the optional parameters
  # @return [Ad]
  describe 'create_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_ad_library_item
  # @param org_id 
  # @param create_ad_library_item_request 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItem]
  describe 'create_ad_library_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_advertiser
  # @param project_id 
  # @param create_advertiser_request 
  # @param [Hash] opts the optional parameters
  # @return [Advertiser]
  describe 'create_advertiser test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_campaign
  # @param project_id 
  # @param create_campaign_request 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'create_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_creative
  # @param project_id 
  # @param create_creative_request 
  # @param [Hash] opts the optional parameters
  # @return [Creative]
  describe 'create_creative test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_creative_template
  # @param project_id 
  # @param create_creative_template_request 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplate]
  describe 'create_creative_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_flight
  # @param project_id 
  # @param create_flight_request 
  # @param [Hash] opts the optional parameters
  # @return [Flight]
  describe 'create_flight test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_project
  # Create a project under an org. Honors &#x60;Idempotency-Key&#x60; (24 h replay window per &#x60;API.md&#x60; \&quot;Idempotency\&quot;); &#x60;409 idempotency_conflict&#x60; if the same key is reused with a different body. Returns &#x60;409 external_id_conflict&#x60; if the &#x60;externalId&#x60; is already taken in this org.
  # @param org_id 
  # @param create_project_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [ProjectResponse]
  describe 'create_project test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_site
  # @param project_id 
  # @param create_site_request 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'create_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_token
  # Mint an opaque token. Returns the plaintext secret exactly once. Min role: org-admin.
  # @param org_id 
  # @param create_token_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateTokenResponse]
  describe 'create_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_zone
  # @param project_id 
  # @param create_zone_request 
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'create_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for decisions
  # @param project_id 
  # @param decisions_request 
  # @param [Hash] opts the optional parameters
  # @return [DecisionsResponse]
  describe 'decisions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for decisions_explain
  # @param project_id 
  # @param decisions_request 
  # @param [Hash] opts the optional parameters
  # @return [ExplainResponse]
  describe 'decisions_explain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ad
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Ad]
  describe 'get_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ad_library_item
  # @param org_id 
  # @param item_id 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItem]
  describe 'get_ad_library_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ad_type
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [AdType]
  describe 'get_ad_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_advertiser
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Advertiser]
  describe 'get_advertiser test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_campaign
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'get_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_channel
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Channel]
  describe 'get_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_creative
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Creative]
  describe 'get_creative test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_creative_template
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplate]
  describe 'get_creative_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_flight
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Flight]
  describe 'get_flight test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_priority
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Priority]
  describe 'get_priority test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_project
  # Read a single project by id (path).
  # @param org_id 
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ProjectResponse]
  describe 'get_project test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_site
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'get_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_zone
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'get_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for healthz
  # Liveness — k8s liveness probe key.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'healthz test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ad_library_items
  # @param org_id 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItemList]
  describe 'list_ad_library_items test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ad_types
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [AdTypeList]
  describe 'list_ad_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ads
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [AdList]
  describe 'list_ads test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_advertisers
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [AdvertiserList]
  describe 'list_advertisers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_campaigns
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [CampaignList]
  describe 'list_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_channels
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ChannelList]
  describe 'list_channels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_creative_templates
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplateList]
  describe 'list_creative_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_creatives
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [CreativeList]
  describe 'list_creatives test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_flights
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [FlightList]
  describe 'list_flights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_priorities
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [PriorityList]
  describe 'list_priorities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sites
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [SiteList]
  describe 'list_sites test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tokens
  # List tokens (metadata only; secrets never leave the mint response). Min role: org-admin.
  # @param org_id 
  # @param [Hash] opts the optional parameters
  # @return [TokenListResponse]
  describe 'list_tokens test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_zones
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ZoneList]
  describe 'list_zones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for readyz
  # Readiness — only 200 when knievel can serve. Per &#x60;REQUIREMENTS.md&#x60; § 10.6, the full check has four criteria; today only the DB-reachability one is real.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'readyz test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_token
  # Revoke a token (soft delete via &#x60;revoked_at&#x60;). The auth path filters revoked rows at the next request. Min role: org-admin.
  # @param org_id 
  # @param token_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_ad
  # @param project_id 
  # @param id 
  # @param update_ad_request 
  # @param [Hash] opts the optional parameters
  # @return [Ad]
  describe 'update_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_ad_library_item
  # @param org_id 
  # @param item_id 
  # @param update_ad_library_item_request 
  # @param [Hash] opts the optional parameters
  # @return [AdLibraryItem]
  describe 'update_ad_library_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_advertiser
  # @param project_id 
  # @param id 
  # @param update_advertiser_request 
  # @param [Hash] opts the optional parameters
  # @return [Advertiser]
  describe 'update_advertiser test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_campaign
  # @param project_id 
  # @param id 
  # @param update_campaign_request 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'update_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_creative_template
  # PATCH bumps &#x60;version&#x60; whenever the schema field is provided (per &#x60;API.md&#x60; § 3.6 — schema changes are versioned but do not retroactively re-validate existing creatives).
  # @param project_id 
  # @param id 
  # @param update_creative_template_request 
  # @param [Hash] opts the optional parameters
  # @return [CreativeTemplate]
  describe 'update_creative_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_flight
  # @param project_id 
  # @param id 
  # @param update_flight_request 
  # @param [Hash] opts the optional parameters
  # @return [Flight]
  describe 'update_flight test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_site
  # @param project_id 
  # @param id 
  # @param update_site_request 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'update_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_zone
  # @param project_id 
  # @param id 
  # @param update_zone_request 
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'update_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_creative_image
  # Multipart image upload (Phase 3.32). Validates the body against the &#x60;image_upload&#x60; core (size + magic bytes + MIME allow-list), writes through the configured &#x60;ImageStore&#x60;, and updates the creative row&#39;s &#x60;image_url&#x60; in the same transaction. Min role: editor (matches &#x60;createCreative&#x60;).
  # @param project_id 
  # @param id 
  # @param file 
  # @param [Hash] opts the optional parameters
  # @return [Creative]
  describe 'upload_creative_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upsert_site_by_url
  # Natural-key upsert. Returns the existing row (200) when a site with the same URL exists; otherwise creates (201). Per &#x60;API.md&#x60; § 3.7: &#x60;:upsertByUrl&#x60; is the canonical entry point for URL-driven flows.
  # @param project_id 
  # @param upsert_site_by_url_request 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'upsert_site_by_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for version
  # Build metadata + effective auth policy.
  # @param [Hash] opts the optional parameters
  # @return [VersionResponse]
  describe 'version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
