=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::FlightsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FlightsApi' do
  before do
    # run before each test
    @api_instance = Knievel::FlightsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FlightsApi' do
    it 'should create an instance of FlightsApi' do
      expect(@api_instance).to be_instance_of(Knievel::FlightsApi)
    end
  end

  # unit tests for batch_upsert_flights
  # @param project_id 
  # @param batch_upsert_flights_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertFlightsResult]
  describe 'batch_upsert_flights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_flight
  # @param project_id 
  # @param create_flight_request 
  # @param [Hash] opts the optional parameters
  # @return [Flight]
  describe 'create_flight test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_flight
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Flight]
  describe 'get_flight test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_flights
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [FlightList]
  describe 'list_flights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_flight
  # @param project_id 
  # @param id 
  # @param update_flight_request 
  # @param [Hash] opts the optional parameters
  # @return [Flight]
  describe 'update_flight test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
