=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::SitesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SitesApi' do
  before do
    # run before each test
    @api_instance = Knievel::SitesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SitesApi' do
    it 'should create an instance of SitesApi' do
      expect(@api_instance).to be_instance_of(Knievel::SitesApi)
    end
  end

  # unit tests for batch_upsert_sites
  # @param project_id 
  # @param batch_upsert_sites_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertSitesResult]
  describe 'batch_upsert_sites test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_site
  # @param project_id 
  # @param create_site_request 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'create_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_site
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'get_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sites
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [SiteList]
  describe 'list_sites test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_site
  # @param project_id 
  # @param id 
  # @param update_site_request 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'update_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upsert_site_by_url
  # Natural-key upsert. Returns the existing row (200) when a site with the same URL exists; otherwise creates (201). Per &#x60;API.md&#x60; § 3.7: &#x60;:upsertByUrl&#x60; is the canonical entry point for URL-driven flows.
  # @param project_id 
  # @param upsert_site_by_url_request 
  # @param [Hash] opts the optional parameters
  # @return [Site]
  describe 'upsert_site_by_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
