=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::SystemApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SystemApi' do
  before do
    # run before each test
    @api_instance = Knievel::SystemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SystemApi' do
    it 'should create an instance of SystemApi' do
      expect(@api_instance).to be_instance_of(Knievel::SystemApi)
    end
  end

  # unit tests for healthz
  # Liveness — k8s liveness probe key.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'healthz test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for readyz
  # Readiness — only 200 when knievel can serve. Per &#x60;REQUIREMENTS.md&#x60; § 10.6, the full check has four criteria; today only the DB-reachability one is real.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'readyz test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for version
  # Build metadata + effective auth policy.
  # @param [Hash] opts the optional parameters
  # @return [VersionResponse]
  describe 'version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
