=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::TaxonomyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxonomyApi' do
  before do
    # run before each test
    @api_instance = Knievel::TaxonomyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxonomyApi' do
    it 'should create an instance of TaxonomyApi' do
      expect(@api_instance).to be_instance_of(Knievel::TaxonomyApi)
    end
  end

  # unit tests for get_ad_type
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [AdType]
  describe 'get_ad_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_channel
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Channel]
  describe 'get_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_priority
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Priority]
  describe 'get_priority test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ad_types
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [AdTypeList]
  describe 'list_ad_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_channels
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ChannelList]
  describe 'list_channels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_priorities
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [PriorityList]
  describe 'list_priorities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
