=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::TokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TokensApi' do
  before do
    # run before each test
    @api_instance = Knievel::TokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TokensApi' do
    it 'should create an instance of TokensApi' do
      expect(@api_instance).to be_instance_of(Knievel::TokensApi)
    end
  end

  # unit tests for create_token
  # Mint an opaque token. Returns the plaintext secret exactly once. Min role: org-admin.
  # @param org_id 
  # @param create_token_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateTokenResponse]
  describe 'create_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tokens
  # List tokens (metadata only; secrets never leave the mint response). Min role: org-admin.
  # @param org_id 
  # @param [Hash] opts the optional parameters
  # @return [TokenListResponse]
  describe 'list_tokens test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_token
  # Revoke a token (soft delete via &#x60;revoked_at&#x60;). The auth path filters revoked rows at the next request. Min role: org-admin.
  # @param org_id 
  # @param token_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
