=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Knievel::ZonesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ZonesApi' do
  before do
    # run before each test
    @api_instance = Knievel::ZonesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ZonesApi' do
    it 'should create an instance of ZonesApi' do
      expect(@api_instance).to be_instance_of(Knievel::ZonesApi)
    end
  end

  # unit tests for batch_upsert_zones
  # @param project_id 
  # @param batch_upsert_zones_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchUpsertZonesResult]
  describe 'batch_upsert_zones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_zone
  # @param project_id 
  # @param create_zone_request 
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'create_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_zone
  # @param project_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'get_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_zones
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ZoneList]
  describe 'list_zones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_zone
  # @param project_id 
  # @param id 
  # @param update_zone_request 
  # @param [Hash] opts the optional parameters
  # @return [Zone]
  describe 'update_zone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
