=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Knievel::CreativeTemplateList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Knievel::CreativeTemplateList do
  #let(:instance) { Knievel::CreativeTemplateList.new }

  describe 'test an instance of CreativeTemplateList' do
    it 'should create an instance of CreativeTemplateList' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Knievel::CreativeTemplateList)
    end
  end

  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "next_cursor"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
