=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.31

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Knievel::DecisionCreativeNativeCreative
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Knievel::DecisionCreativeNativeCreative do
  #let(:instance) { Knievel::DecisionCreativeNativeCreative.new }

  describe 'test an instance of DecisionCreativeNativeCreative' do
    it 'should create an instance of DecisionCreativeNativeCreative' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Knievel::DecisionCreativeNativeCreative)
    end
  end

  describe 'test attribute "template"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "values"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "click_through_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["native"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
