=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.24

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

# Common files
require 'knievel/api_client'
require 'knievel/api_error'
require 'knievel/api_model_base'
require 'knievel/version'
require 'knievel/configuration'

# Models
require 'knievel/models/ad'
require 'knievel/models/ad_library_item'
require 'knievel/models/ad_library_item_list'
require 'knievel/models/ad_list'
require 'knievel/models/ad_type'
require 'knievel/models/ad_type_list'
require 'knievel/models/advertiser'
require 'knievel/models/advertiser_list'
require 'knievel/models/auth_block'
require 'knievel/models/batch_error_body'
require 'knievel/models/batch_error_detail'
require 'knievel/models/batch_error_envelope'
require 'knievel/models/batch_upsert_ad_row'
require 'knievel/models/batch_upsert_ads_request'
require 'knievel/models/batch_upsert_ads_result'
require 'knievel/models/batch_upsert_advertiser_row'
require 'knievel/models/batch_upsert_advertisers_request'
require 'knievel/models/batch_upsert_advertisers_result'
require 'knievel/models/batch_upsert_campaign_row'
require 'knievel/models/batch_upsert_campaigns_request'
require 'knievel/models/batch_upsert_campaigns_result'
require 'knievel/models/batch_upsert_flight_row'
require 'knievel/models/batch_upsert_flights_request'
require 'knievel/models/batch_upsert_flights_result'
require 'knievel/models/batch_upsert_site_row'
require 'knievel/models/batch_upsert_sites_request'
require 'knievel/models/batch_upsert_sites_result'
require 'knievel/models/batch_upsert_zone_row'
require 'knievel/models/batch_upsert_zones_request'
require 'knievel/models/batch_upsert_zones_result'
require 'knievel/models/campaign'
require 'knievel/models/campaign_list'
require 'knievel/models/channel'
require 'knievel/models/channel_list'
require 'knievel/models/create_ad_library_item_request'
require 'knievel/models/create_ad_request'
require 'knievel/models/create_advertiser_request'
require 'knievel/models/create_campaign_request'
require 'knievel/models/create_creative_request'
require 'knievel/models/create_creative_template_request'
require 'knievel/models/create_flight_request'
require 'knievel/models/create_project_request'
require 'knievel/models/create_site_request'
require 'knievel/models/create_token_request'
require 'knievel/models/create_token_response'
require 'knievel/models/create_zone_request'
require 'knievel/models/creative'
require 'knievel/models/creative_list'
require 'knievel/models/creative_template'
require 'knievel/models/creative_template_list'
require 'knievel/models/decision_ad'
require 'knievel/models/decision_block'
require 'knievel/models/decision_context'
require 'knievel/models/decision_placement'
require 'knievel/models/decisions_request'
require 'knievel/models/decisions_response'
require 'knievel/models/error_body'
require 'knievel/models/error_envelope'
require 'knievel/models/explain_candidate'
require 'knievel/models/explain_evaluation'
require 'knievel/models/explain_placement'
require 'knievel/models/explain_response'
require 'knievel/models/flight'
require 'knievel/models/flight_list'
require 'knievel/models/force_override'
require 'knievel/models/issuer_summary'
require 'knievel/models/org_response'
require 'knievel/models/priority'
require 'knievel/models/priority_list'
require 'knievel/models/project_list'
require 'knievel/models/project_response'
require 'knievel/models/site'
require 'knievel/models/site_list'
require 'knievel/models/token_list_response'
require 'knievel/models/token_summary'
require 'knievel/models/update_ad_library_item_request'
require 'knievel/models/update_ad_request'
require 'knievel/models/update_advertiser_request'
require 'knievel/models/update_campaign_request'
require 'knievel/models/update_creative_template_request'
require 'knievel/models/update_flight_request'
require 'knievel/models/update_site_request'
require 'knievel/models/update_zone_request'
require 'knievel/models/upsert_site_by_url_request'
require 'knievel/models/version_response'
require 'knievel/models/whoami_response'
require 'knievel/models/zone'
require 'knievel/models/zone_list'

# APIs
require 'knievel/api/ad_library_api'
require 'knievel/api/ads_api'
require 'knievel/api/advertisers_api'
require 'knievel/api/auth_api'
require 'knievel/api/campaigns_api'
require 'knievel/api/creative_templates_api'
require 'knievel/api/creatives_api'
require 'knievel/api/decisions_api'
require 'knievel/api/explain_api'
require 'knievel/api/flights_api'
require 'knievel/api/orgs_api'
require 'knievel/api/sites_api'
require 'knievel/api/system_api'
require 'knievel/api/taxonomy_api'
require 'knievel/api/tokens_api'
require 'knievel/api/zones_api'

module Knievel
  class << self
    # Customize default settings for the SDK using block.
    #   Knievel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
