=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.16

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'date'
require 'time'

module Knievel
  class ExplainCandidate < ApiModelBase
    attr_accessor :ad_id

    attr_accessor :creative_id

    attr_accessor :flight_id

    attr_accessor :campaign_id

    attr_accessor :advertiser_id

    attr_accessor :weight

    attr_accessor :evaluation

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ad_id' => :'ad_id',
        :'creative_id' => :'creative_id',
        :'flight_id' => :'flight_id',
        :'campaign_id' => :'campaign_id',
        :'advertiser_id' => :'advertiser_id',
        :'weight' => :'weight',
        :'evaluation' => :'evaluation'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ad_id' => :'Integer',
        :'creative_id' => :'Integer',
        :'flight_id' => :'Integer',
        :'campaign_id' => :'Integer',
        :'advertiser_id' => :'Integer',
        :'weight' => :'Integer',
        :'evaluation' => :'Array<ExplainEvaluation>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Knievel::ExplainCandidate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Knievel::ExplainCandidate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ad_id')
        self.ad_id = attributes[:'ad_id']
      else
        self.ad_id = nil
      end

      if attributes.key?(:'creative_id')
        self.creative_id = attributes[:'creative_id']
      else
        self.creative_id = nil
      end

      if attributes.key?(:'flight_id')
        self.flight_id = attributes[:'flight_id']
      else
        self.flight_id = nil
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      else
        self.campaign_id = nil
      end

      if attributes.key?(:'advertiser_id')
        self.advertiser_id = attributes[:'advertiser_id']
      else
        self.advertiser_id = nil
      end

      if attributes.key?(:'weight')
        self.weight = attributes[:'weight']
      else
        self.weight = nil
      end

      if attributes.key?(:'evaluation')
        if (value = attributes[:'evaluation']).is_a?(Array)
          self.evaluation = value
        end
      else
        self.evaluation = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @ad_id.nil?
        invalid_properties.push('invalid value for "ad_id", ad_id cannot be nil.')
      end

      if @creative_id.nil?
        invalid_properties.push('invalid value for "creative_id", creative_id cannot be nil.')
      end

      if @flight_id.nil?
        invalid_properties.push('invalid value for "flight_id", flight_id cannot be nil.')
      end

      if @campaign_id.nil?
        invalid_properties.push('invalid value for "campaign_id", campaign_id cannot be nil.')
      end

      if @advertiser_id.nil?
        invalid_properties.push('invalid value for "advertiser_id", advertiser_id cannot be nil.')
      end

      if @weight.nil?
        invalid_properties.push('invalid value for "weight", weight cannot be nil.')
      end

      if @evaluation.nil?
        invalid_properties.push('invalid value for "evaluation", evaluation cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @ad_id.nil?
      return false if @creative_id.nil?
      return false if @flight_id.nil?
      return false if @campaign_id.nil?
      return false if @advertiser_id.nil?
      return false if @weight.nil?
      return false if @evaluation.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_id Value to be assigned
    def ad_id=(ad_id)
      if ad_id.nil?
        fail ArgumentError, 'ad_id cannot be nil'
      end

      @ad_id = ad_id
    end

    # Custom attribute writer method with validation
    # @param [Object] creative_id Value to be assigned
    def creative_id=(creative_id)
      if creative_id.nil?
        fail ArgumentError, 'creative_id cannot be nil'
      end

      @creative_id = creative_id
    end

    # Custom attribute writer method with validation
    # @param [Object] flight_id Value to be assigned
    def flight_id=(flight_id)
      if flight_id.nil?
        fail ArgumentError, 'flight_id cannot be nil'
      end

      @flight_id = flight_id
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign_id Value to be assigned
    def campaign_id=(campaign_id)
      if campaign_id.nil?
        fail ArgumentError, 'campaign_id cannot be nil'
      end

      @campaign_id = campaign_id
    end

    # Custom attribute writer method with validation
    # @param [Object] advertiser_id Value to be assigned
    def advertiser_id=(advertiser_id)
      if advertiser_id.nil?
        fail ArgumentError, 'advertiser_id cannot be nil'
      end

      @advertiser_id = advertiser_id
    end

    # Custom attribute writer method with validation
    # @param [Object] weight Value to be assigned
    def weight=(weight)
      if weight.nil?
        fail ArgumentError, 'weight cannot be nil'
      end

      @weight = weight
    end

    # Custom attribute writer method with validation
    # @param [Object] evaluation Value to be assigned
    def evaluation=(evaluation)
      if evaluation.nil?
        fail ArgumentError, 'evaluation cannot be nil'
      end

      @evaluation = evaluation
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ad_id == o.ad_id &&
          creative_id == o.creative_id &&
          flight_id == o.flight_id &&
          campaign_id == o.campaign_id &&
          advertiser_id == o.advertiser_id &&
          weight == o.weight &&
          evaluation == o.evaluation
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ad_id, creative_id, flight_id, campaign_id, advertiser_id, weight, evaluation].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
