=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.31

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'date'
require 'time'

module Knievel
  class Flight < ApiModelBase
    attr_accessor :id

    attr_accessor :external_id

    attr_accessor :campaign_id

    attr_accessor :name

    attr_accessor :priority_id

    attr_accessor :start_date

    attr_accessor :end_date

    attr_accessor :site_ids

    attr_accessor :zone_ids

    attr_accessor :ad_types

    attr_accessor :is_active

    attr_accessor :etag

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'external_id' => :'external_id',
        :'campaign_id' => :'campaign_id',
        :'name' => :'name',
        :'priority_id' => :'priority_id',
        :'start_date' => :'start_date',
        :'end_date' => :'end_date',
        :'site_ids' => :'site_ids',
        :'zone_ids' => :'zone_ids',
        :'ad_types' => :'ad_types',
        :'is_active' => :'is_active',
        :'etag' => :'etag',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'external_id' => :'String',
        :'campaign_id' => :'Integer',
        :'name' => :'String',
        :'priority_id' => :'Integer',
        :'start_date' => :'String',
        :'end_date' => :'String',
        :'site_ids' => :'Array<Integer>',
        :'zone_ids' => :'Array<Integer>',
        :'ad_types' => :'Array<Integer>',
        :'is_active' => :'Boolean',
        :'etag' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Knievel::Flight` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Knievel::Flight`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      else
        self.campaign_id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'priority_id')
        self.priority_id = attributes[:'priority_id']
      else
        self.priority_id = nil
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'end_date')
        self.end_date = attributes[:'end_date']
      end

      if attributes.key?(:'site_ids')
        if (value = attributes[:'site_ids']).is_a?(Array)
          self.site_ids = value
        end
      else
        self.site_ids = nil
      end

      if attributes.key?(:'zone_ids')
        if (value = attributes[:'zone_ids']).is_a?(Array)
          self.zone_ids = value
        end
      else
        self.zone_ids = nil
      end

      if attributes.key?(:'ad_types')
        if (value = attributes[:'ad_types']).is_a?(Array)
          self.ad_types = value
        end
      else
        self.ad_types = nil
      end

      if attributes.key?(:'is_active')
        self.is_active = attributes[:'is_active']
      else
        self.is_active = nil
      end

      if attributes.key?(:'etag')
        self.etag = attributes[:'etag']
      else
        self.etag = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @campaign_id.nil?
        invalid_properties.push('invalid value for "campaign_id", campaign_id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @priority_id.nil?
        invalid_properties.push('invalid value for "priority_id", priority_id cannot be nil.')
      end

      if @site_ids.nil?
        invalid_properties.push('invalid value for "site_ids", site_ids cannot be nil.')
      end

      if @zone_ids.nil?
        invalid_properties.push('invalid value for "zone_ids", zone_ids cannot be nil.')
      end

      if @ad_types.nil?
        invalid_properties.push('invalid value for "ad_types", ad_types cannot be nil.')
      end

      if @is_active.nil?
        invalid_properties.push('invalid value for "is_active", is_active cannot be nil.')
      end

      if @etag.nil?
        invalid_properties.push('invalid value for "etag", etag cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @campaign_id.nil?
      return false if @name.nil?
      return false if @priority_id.nil?
      return false if @site_ids.nil?
      return false if @zone_ids.nil?
      return false if @ad_types.nil?
      return false if @is_active.nil?
      return false if @etag.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign_id Value to be assigned
    def campaign_id=(campaign_id)
      if campaign_id.nil?
        fail ArgumentError, 'campaign_id cannot be nil'
      end

      @campaign_id = campaign_id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] priority_id Value to be assigned
    def priority_id=(priority_id)
      if priority_id.nil?
        fail ArgumentError, 'priority_id cannot be nil'
      end

      @priority_id = priority_id
    end

    # Custom attribute writer method with validation
    # @param [Object] site_ids Value to be assigned
    def site_ids=(site_ids)
      if site_ids.nil?
        fail ArgumentError, 'site_ids cannot be nil'
      end

      @site_ids = site_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] zone_ids Value to be assigned
    def zone_ids=(zone_ids)
      if zone_ids.nil?
        fail ArgumentError, 'zone_ids cannot be nil'
      end

      @zone_ids = zone_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_types Value to be assigned
    def ad_types=(ad_types)
      if ad_types.nil?
        fail ArgumentError, 'ad_types cannot be nil'
      end

      @ad_types = ad_types
    end

    # Custom attribute writer method with validation
    # @param [Object] is_active Value to be assigned
    def is_active=(is_active)
      if is_active.nil?
        fail ArgumentError, 'is_active cannot be nil'
      end

      @is_active = is_active
    end

    # Custom attribute writer method with validation
    # @param [Object] etag Value to be assigned
    def etag=(etag)
      if etag.nil?
        fail ArgumentError, 'etag cannot be nil'
      end

      @etag = etag
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          external_id == o.external_id &&
          campaign_id == o.campaign_id &&
          name == o.name &&
          priority_id == o.priority_id &&
          start_date == o.start_date &&
          end_date == o.end_date &&
          site_ids == o.site_ids &&
          zone_ids == o.zone_ids &&
          ad_types == o.ad_types &&
          is_active == o.is_active &&
          etag == o.etag &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, external_id, campaign_id, name, priority_id, start_date, end_date, site_ids, zone_ids, ad_types, is_active, etag, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
