=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.23

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'date'
require 'time'

module Knievel
  # Build metadata + effective auth policy. Per `API.md` § 5 and `AUTH.md` \"Effective-policy visibility.\" `auth.modes` lists the enabled credential types (`opaque`, `jwt`); `auth.issuers` summarizes each configured JWT issuer with its audience, algorithms, claim source, and JWKS URL. Secrets are never returned.
  class VersionResponse < ApiModelBase
    attr_accessor :knievel

    attr_accessor :schema

    attr_accessor :git_sha

    attr_accessor :build_timestamp

    attr_accessor :auth

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'knievel' => :'knievel',
        :'schema' => :'schema',
        :'git_sha' => :'git_sha',
        :'build_timestamp' => :'build_timestamp',
        :'auth' => :'auth'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'knievel' => :'String',
        :'schema' => :'String',
        :'git_sha' => :'String',
        :'build_timestamp' => :'String',
        :'auth' => :'AuthBlock'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Knievel::VersionResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Knievel::VersionResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'knievel')
        self.knievel = attributes[:'knievel']
      else
        self.knievel = nil
      end

      if attributes.key?(:'schema')
        self.schema = attributes[:'schema']
      else
        self.schema = nil
      end

      if attributes.key?(:'git_sha')
        self.git_sha = attributes[:'git_sha']
      else
        self.git_sha = nil
      end

      if attributes.key?(:'build_timestamp')
        self.build_timestamp = attributes[:'build_timestamp']
      else
        self.build_timestamp = nil
      end

      if attributes.key?(:'auth')
        self.auth = attributes[:'auth']
      else
        self.auth = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @knievel.nil?
        invalid_properties.push('invalid value for "knievel", knievel cannot be nil.')
      end

      if @schema.nil?
        invalid_properties.push('invalid value for "schema", schema cannot be nil.')
      end

      if @git_sha.nil?
        invalid_properties.push('invalid value for "git_sha", git_sha cannot be nil.')
      end

      if @build_timestamp.nil?
        invalid_properties.push('invalid value for "build_timestamp", build_timestamp cannot be nil.')
      end

      if @auth.nil?
        invalid_properties.push('invalid value for "auth", auth cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @knievel.nil?
      return false if @schema.nil?
      return false if @git_sha.nil?
      return false if @build_timestamp.nil?
      return false if @auth.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] knievel Value to be assigned
    def knievel=(knievel)
      if knievel.nil?
        fail ArgumentError, 'knievel cannot be nil'
      end

      @knievel = knievel
    end

    # Custom attribute writer method with validation
    # @param [Object] schema Value to be assigned
    def schema=(schema)
      if schema.nil?
        fail ArgumentError, 'schema cannot be nil'
      end

      @schema = schema
    end

    # Custom attribute writer method with validation
    # @param [Object] git_sha Value to be assigned
    def git_sha=(git_sha)
      if git_sha.nil?
        fail ArgumentError, 'git_sha cannot be nil'
      end

      @git_sha = git_sha
    end

    # Custom attribute writer method with validation
    # @param [Object] build_timestamp Value to be assigned
    def build_timestamp=(build_timestamp)
      if build_timestamp.nil?
        fail ArgumentError, 'build_timestamp cannot be nil'
      end

      @build_timestamp = build_timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] auth Value to be assigned
    def auth=(auth)
      if auth.nil?
        fail ArgumentError, 'auth cannot be nil'
      end

      @auth = auth
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          knievel == o.knievel &&
          schema == o.schema &&
          git_sha == o.git_sha &&
          build_timestamp == o.build_timestamp &&
          auth == o.auth
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [knievel, schema, git_sha, build_timestamp, auth].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
