=begin
#knievel

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.31

Generated by: https://openapi-generator.tech
Generator version: 7.23.0-SNAPSHOT

=end

require 'date'
require 'time'

module Knievel
  class WhoamiResponse < ApiModelBase
    # `org` or `project`.
    attr_accessor :scope

    attr_accessor :org_id

    # Present only when `scope == \"project\"`.
    attr_accessor :project_id

    # One of `org-owner`, `org-admin`, `admin`, `editor`, `reader`.
    attr_accessor :role

    # `opaque` for `kvl_*` bearers; `jwt` for OIDC bearers.
    attr_accessor :token_type

    # Opaque actor identifier; matches `audit_log.actor`.
    attr_accessor :actor_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'scope' => :'scope',
        :'org_id' => :'org_id',
        :'project_id' => :'project_id',
        :'role' => :'role',
        :'token_type' => :'token_type',
        :'actor_id' => :'actor_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'scope' => :'String',
        :'org_id' => :'String',
        :'project_id' => :'String',
        :'role' => :'String',
        :'token_type' => :'String',
        :'actor_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Knievel::WhoamiResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Knievel::WhoamiResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'scope')
        self.scope = attributes[:'scope']
      else
        self.scope = nil
      end

      if attributes.key?(:'org_id')
        self.org_id = attributes[:'org_id']
      else
        self.org_id = nil
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      else
        self.role = nil
      end

      if attributes.key?(:'token_type')
        self.token_type = attributes[:'token_type']
      else
        self.token_type = nil
      end

      if attributes.key?(:'actor_id')
        self.actor_id = attributes[:'actor_id']
      else
        self.actor_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @scope.nil?
        invalid_properties.push('invalid value for "scope", scope cannot be nil.')
      end

      if @org_id.nil?
        invalid_properties.push('invalid value for "org_id", org_id cannot be nil.')
      end

      if @role.nil?
        invalid_properties.push('invalid value for "role", role cannot be nil.')
      end

      if @token_type.nil?
        invalid_properties.push('invalid value for "token_type", token_type cannot be nil.')
      end

      if @actor_id.nil?
        invalid_properties.push('invalid value for "actor_id", actor_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @scope.nil?
      return false if @org_id.nil?
      return false if @role.nil?
      return false if @token_type.nil?
      return false if @actor_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] scope Value to be assigned
    def scope=(scope)
      if scope.nil?
        fail ArgumentError, 'scope cannot be nil'
      end

      @scope = scope
    end

    # Custom attribute writer method with validation
    # @param [Object] org_id Value to be assigned
    def org_id=(org_id)
      if org_id.nil?
        fail ArgumentError, 'org_id cannot be nil'
      end

      @org_id = org_id
    end

    # Custom attribute writer method with validation
    # @param [Object] role Value to be assigned
    def role=(role)
      if role.nil?
        fail ArgumentError, 'role cannot be nil'
      end

      @role = role
    end

    # Custom attribute writer method with validation
    # @param [Object] token_type Value to be assigned
    def token_type=(token_type)
      if token_type.nil?
        fail ArgumentError, 'token_type cannot be nil'
      end

      @token_type = token_type
    end

    # Custom attribute writer method with validation
    # @param [Object] actor_id Value to be assigned
    def actor_id=(actor_id)
      if actor_id.nil?
        fail ArgumentError, 'actor_id cannot be nil'
      end

      @actor_id = actor_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          scope == o.scope &&
          org_id == o.org_id &&
          project_id == o.project_id &&
          role == o.role &&
          token_type == o.token_type &&
          actor_id == o.actor_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [scope, org_id, project_id, role, token_type, actor_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
